#!/usr/bin/env bash

STATUS=$(playerctl status)

# Let it be prepared for customization on several play modes :)
case $STATUS in
 "Playing") STATUS_ICON="";;
esac

# Get info.
ARTIST=$(playerctl metadata xesam:artist)
TITLE=$(playerctl metadata xesam:title)

## ncmpcpp mode.
# ARTIST=$(ncmpcpp --current-song="%a")
# TITLE=$(ncmpcpp --current-song="%t")

# Only show when playing.
if [[ $STATUS == "Playing" ]]; then
  echo "$ARTIST - $TITLE" # full_text
  echo "$STATUS_ICON"
  echo "#2ebd59" # color
fi
