#!/usr/bin/env bash

# create tmp.
_INPUT_FILE=$(mktemp)

# i3 will make this a scratch window based on the class.
i3-sensible-terminal --name __scratchpad --exec "vim -c 'set noswapfile wrap linebreak ft=text spell spelllang=es_es noexpandtab showtabline=0' '$_INPUT_FILE'"

# delay.
sleep 0.2

# strip last byte, the newline. https://stackoverflow.com/a/12579554
head -c -1 "$_INPUT_FILE" | xdotool type --clearmodifiers --delay 0 --file -

# clean tmp.
rm -f "$_INPUT_FILE">/dev/null
