#!/usr/bin/env bash

lock_script="$HOME/.config/i3/scripts/lock"
lock_picture="$HOME/.config/i3/images/lock.png"

case "$1" in
    lock)
        sleep 1
        source $lock_script -d /tmp -b -s -o $lock_picture -n
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        sleep 1
        source $lock_script -d /tmp -b -s -o $lock_picture
        systemctl suspend
        ;;
    hibernate)
        sleep 1
        source $lock_script -d /tmp -b -s -o $lock_picture
        systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 [lock|logout|suspend|hibernate|reboot|shutdown]"
        exit 2
esac

exit 0
