icons = "awesome"

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#073642"

[[block]]
block = "music"
player = "spotify"

[[block]]
block = "custom"
interval = 1
command = "$HOME/.config/i3/blocks/volume 1"

[[block]]
block = "custom"
interval = 1
command = "$HOME/.config/i3/blocks/wifi || $HOME/.config/i3/blocks/ethernet || Disconnected"

# [[block]]
# block = "xrandr"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

# [[block]]
# block = "sound"

[[block]]
block = "temperature"

[[block]]
block = "battery"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

# vim: ft=toml cms=#%s
